# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.13.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.13.3/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/callum/Documents/Year 4/thesis/monte_carlo_raytracer"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/callum/Documents/Year 4/thesis/monte_carlo_raytracer"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.13.3/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.10.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/callum/Documents/Year 4/thesis/monte_carlo_raytracer/CMakeFiles" "/Users/callum/Documents/Year 4/thesis/monte_carlo_raytracer/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/callum/Documents/Year 4/thesis/monte_carlo_raytracer/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Monte_Carlo_Raytracer

# Build rule for target.
Monte_Carlo_Raytracer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Monte_Carlo_Raytracer
.PHONY : Monte_Carlo_Raytracer

# fast build rule for target.
Monte_Carlo_Raytracer/fast:
	$(MAKE) -f CMakeFiles/Monte_Carlo_Raytracer.dir/build.make CMakeFiles/Monte_Carlo_Raytracer.dir/build
.PHONY : Monte_Carlo_Raytracer/fast

Source/camera.o: Source/camera.cpp.o

.PHONY : Source/camera.o

# target to build an object file
Source/camera.cpp.o:
	$(MAKE) -f CMakeFiles/Monte_Carlo_Raytracer.dir/build.make CMakeFiles/Monte_Carlo_Raytracer.dir/Source/camera.cpp.o
.PHONY : Source/camera.cpp.o

Source/camera.i: Source/camera.cpp.i

.PHONY : Source/camera.i

# target to preprocess a source file
Source/camera.cpp.i:
	$(MAKE) -f CMakeFiles/Monte_Carlo_Raytracer.dir/build.make CMakeFiles/Monte_Carlo_Raytracer.dir/Source/camera.cpp.i
.PHONY : Source/camera.cpp.i

Source/camera.s: Source/camera.cpp.s

.PHONY : Source/camera.s

# target to generate assembly for a file
Source/camera.cpp.s:
	$(MAKE) -f CMakeFiles/Monte_Carlo_Raytracer.dir/build.make CMakeFiles/Monte_Carlo_Raytracer.dir/Source/camera.cpp.s
.PHONY : Source/camera.cpp.s

Source/main.o: Source/main.cpp.o

.PHONY : Source/main.o

# target to build an object file
Source/main.cpp.o:
	$(MAKE) -f CMakeFiles/Monte_Carlo_Raytracer.dir/build.make CMakeFiles/Monte_Carlo_Raytracer.dir/Source/main.cpp.o
.PHONY : Source/main.cpp.o

Source/main.i: Source/main.cpp.i

.PHONY : Source/main.i

# target to preprocess a source file
Source/main.cpp.i:
	$(MAKE) -f CMakeFiles/Monte_Carlo_Raytracer.dir/build.make CMakeFiles/Monte_Carlo_Raytracer.dir/Source/main.cpp.i
.PHONY : Source/main.cpp.i

Source/main.s: Source/main.cpp.s

.PHONY : Source/main.s

# target to generate assembly for a file
Source/main.cpp.s:
	$(MAKE) -f CMakeFiles/Monte_Carlo_Raytracer.dir/build.make CMakeFiles/Monte_Carlo_Raytracer.dir/Source/main.cpp.s
.PHONY : Source/main.cpp.s

Source/objects/material.o: Source/objects/material.cpp.o

.PHONY : Source/objects/material.o

# target to build an object file
Source/objects/material.cpp.o:
	$(MAKE) -f CMakeFiles/Monte_Carlo_Raytracer.dir/build.make CMakeFiles/Monte_Carlo_Raytracer.dir/Source/objects/material.cpp.o
.PHONY : Source/objects/material.cpp.o

Source/objects/material.i: Source/objects/material.cpp.i

.PHONY : Source/objects/material.i

# target to preprocess a source file
Source/objects/material.cpp.i:
	$(MAKE) -f CMakeFiles/Monte_Carlo_Raytracer.dir/build.make CMakeFiles/Monte_Carlo_Raytracer.dir/Source/objects/material.cpp.i
.PHONY : Source/objects/material.cpp.i

Source/objects/material.s: Source/objects/material.cpp.s

.PHONY : Source/objects/material.s

# target to generate assembly for a file
Source/objects/material.cpp.s:
	$(MAKE) -f CMakeFiles/Monte_Carlo_Raytracer.dir/build.make CMakeFiles/Monte_Carlo_Raytracer.dir/Source/objects/material.cpp.s
.PHONY : Source/objects/material.cpp.s

Source/objects/shape.o: Source/objects/shape.cpp.o

.PHONY : Source/objects/shape.o

# target to build an object file
Source/objects/shape.cpp.o:
	$(MAKE) -f CMakeFiles/Monte_Carlo_Raytracer.dir/build.make CMakeFiles/Monte_Carlo_Raytracer.dir/Source/objects/shape.cpp.o
.PHONY : Source/objects/shape.cpp.o

Source/objects/shape.i: Source/objects/shape.cpp.i

.PHONY : Source/objects/shape.i

# target to preprocess a source file
Source/objects/shape.cpp.i:
	$(MAKE) -f CMakeFiles/Monte_Carlo_Raytracer.dir/build.make CMakeFiles/Monte_Carlo_Raytracer.dir/Source/objects/shape.cpp.i
.PHONY : Source/objects/shape.cpp.i

Source/objects/shape.s: Source/objects/shape.cpp.s

.PHONY : Source/objects/shape.s

# target to generate assembly for a file
Source/objects/shape.cpp.s:
	$(MAKE) -f CMakeFiles/Monte_Carlo_Raytracer.dir/build.make CMakeFiles/Monte_Carlo_Raytracer.dir/Source/objects/shape.cpp.s
.PHONY : Source/objects/shape.cpp.s

Source/objects/triangle.o: Source/objects/triangle.cpp.o

.PHONY : Source/objects/triangle.o

# target to build an object file
Source/objects/triangle.cpp.o:
	$(MAKE) -f CMakeFiles/Monte_Carlo_Raytracer.dir/build.make CMakeFiles/Monte_Carlo_Raytracer.dir/Source/objects/triangle.cpp.o
.PHONY : Source/objects/triangle.cpp.o

Source/objects/triangle.i: Source/objects/triangle.cpp.i

.PHONY : Source/objects/triangle.i

# target to preprocess a source file
Source/objects/triangle.cpp.i:
	$(MAKE) -f CMakeFiles/Monte_Carlo_Raytracer.dir/build.make CMakeFiles/Monte_Carlo_Raytracer.dir/Source/objects/triangle.cpp.i
.PHONY : Source/objects/triangle.cpp.i

Source/objects/triangle.s: Source/objects/triangle.cpp.s

.PHONY : Source/objects/triangle.s

# target to generate assembly for a file
Source/objects/triangle.cpp.s:
	$(MAKE) -f CMakeFiles/Monte_Carlo_Raytracer.dir/build.make CMakeFiles/Monte_Carlo_Raytracer.dir/Source/objects/triangle.cpp.s
.PHONY : Source/objects/triangle.cpp.s

Source/ray.o: Source/ray.cpp.o

.PHONY : Source/ray.o

# target to build an object file
Source/ray.cpp.o:
	$(MAKE) -f CMakeFiles/Monte_Carlo_Raytracer.dir/build.make CMakeFiles/Monte_Carlo_Raytracer.dir/Source/ray.cpp.o
.PHONY : Source/ray.cpp.o

Source/ray.i: Source/ray.cpp.i

.PHONY : Source/ray.i

# target to preprocess a source file
Source/ray.cpp.i:
	$(MAKE) -f CMakeFiles/Monte_Carlo_Raytracer.dir/build.make CMakeFiles/Monte_Carlo_Raytracer.dir/Source/ray.cpp.i
.PHONY : Source/ray.cpp.i

Source/ray.s: Source/ray.cpp.s

.PHONY : Source/ray.s

# target to generate assembly for a file
Source/ray.cpp.s:
	$(MAKE) -f CMakeFiles/Monte_Carlo_Raytracer.dir/build.make CMakeFiles/Monte_Carlo_Raytracer.dir/Source/ray.cpp.s
.PHONY : Source/ray.cpp.s

Source/scenes/cornell_box_scene.o: Source/scenes/cornell_box_scene.cpp.o

.PHONY : Source/scenes/cornell_box_scene.o

# target to build an object file
Source/scenes/cornell_box_scene.cpp.o:
	$(MAKE) -f CMakeFiles/Monte_Carlo_Raytracer.dir/build.make CMakeFiles/Monte_Carlo_Raytracer.dir/Source/scenes/cornell_box_scene.cpp.o
.PHONY : Source/scenes/cornell_box_scene.cpp.o

Source/scenes/cornell_box_scene.i: Source/scenes/cornell_box_scene.cpp.i

.PHONY : Source/scenes/cornell_box_scene.i

# target to preprocess a source file
Source/scenes/cornell_box_scene.cpp.i:
	$(MAKE) -f CMakeFiles/Monte_Carlo_Raytracer.dir/build.make CMakeFiles/Monte_Carlo_Raytracer.dir/Source/scenes/cornell_box_scene.cpp.i
.PHONY : Source/scenes/cornell_box_scene.cpp.i

Source/scenes/cornell_box_scene.s: Source/scenes/cornell_box_scene.cpp.s

.PHONY : Source/scenes/cornell_box_scene.s

# target to generate assembly for a file
Source/scenes/cornell_box_scene.cpp.s:
	$(MAKE) -f CMakeFiles/Monte_Carlo_Raytracer.dir/build.make CMakeFiles/Monte_Carlo_Raytracer.dir/Source/scenes/cornell_box_scene.cpp.s
.PHONY : Source/scenes/cornell_box_scene.cpp.s

Source/utils/printing.o: Source/utils/printing.cpp.o

.PHONY : Source/utils/printing.o

# target to build an object file
Source/utils/printing.cpp.o:
	$(MAKE) -f CMakeFiles/Monte_Carlo_Raytracer.dir/build.make CMakeFiles/Monte_Carlo_Raytracer.dir/Source/utils/printing.cpp.o
.PHONY : Source/utils/printing.cpp.o

Source/utils/printing.i: Source/utils/printing.cpp.i

.PHONY : Source/utils/printing.i

# target to preprocess a source file
Source/utils/printing.cpp.i:
	$(MAKE) -f CMakeFiles/Monte_Carlo_Raytracer.dir/build.make CMakeFiles/Monte_Carlo_Raytracer.dir/Source/utils/printing.cpp.i
.PHONY : Source/utils/printing.cpp.i

Source/utils/printing.s: Source/utils/printing.cpp.s

.PHONY : Source/utils/printing.s

# target to generate assembly for a file
Source/utils/printing.cpp.s:
	$(MAKE) -f CMakeFiles/Monte_Carlo_Raytracer.dir/build.make CMakeFiles/Monte_Carlo_Raytracer.dir/Source/utils/printing.cpp.s
.PHONY : Source/utils/printing.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Monte_Carlo_Raytracer"
	@echo "... Source/camera.o"
	@echo "... Source/camera.i"
	@echo "... Source/camera.s"
	@echo "... Source/main.o"
	@echo "... Source/main.i"
	@echo "... Source/main.s"
	@echo "... Source/objects/material.o"
	@echo "... Source/objects/material.i"
	@echo "... Source/objects/material.s"
	@echo "... Source/objects/shape.o"
	@echo "... Source/objects/shape.i"
	@echo "... Source/objects/shape.s"
	@echo "... Source/objects/triangle.o"
	@echo "... Source/objects/triangle.i"
	@echo "... Source/objects/triangle.s"
	@echo "... Source/ray.o"
	@echo "... Source/ray.i"
	@echo "... Source/ray.s"
	@echo "... Source/scenes/cornell_box_scene.o"
	@echo "... Source/scenes/cornell_box_scene.i"
	@echo "... Source/scenes/cornell_box_scene.s"
	@echo "... Source/utils/printing.o"
	@echo "... Source/utils/printing.i"
	@echo "... Source/utils/printing.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

